### ISSUE TITLE
Container stops execution due to logs existing

### ISSUE THREAD

**Issue by expl0ratory** [mrlt8/docker-wyze-bridge#1242]
## Describe the bug

Since early may, I've been unable to start the bridge container from home assistant.  Shortly after migrating configuration, and setting a wyze api key (this worked fine) it stopped being able to run with the following logs:

[x] Home Asisstant add on

```
[WyzeBridge] 🏠 Home Assistant Mode
[WyzeBridge] Logging to file: /config/wyze-bridge/logs/debug.log
CLEANUP: MIGRATING old='/config/wyze-bridge/' to new='/config/'
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 953, in run_command
    raise e from None
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 335, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/frontend.py", line 17, in <module>
    from wyze_bridge import WyzeBridge
  File "/app/wyze_bridge.py", line 6, in <module>
    from wyzebridge import config
  File "/app/wyzebridge/config.py", line 74, in <module>
    migrate_path("/config/wyze-bridge/", "/config/")
  File "/app/wyzebridge/bridge_utils.py", line 113, in migrate_path
    shutil.move(os.path.join(old, filename), os.path.join(new, filename))
  File "/usr/local/lib/python3.12/shutil.py", line 884, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/config/logs/logs' already exists```

**Comment by mrlt8** [comment]
Are you by any chance running an older version of home assistant?

**Comment by expl0ratory** [comment]
2024.5.5

**Comment by mrlt8** [comment]
I was able to replicate to replicate the issue, and the fix will be in the next release.
