### ISSUE TITLE
Error with webRTc

### ISSUE THREAD

**Issue by haamro** [mrlt8/docker-wyze-bridge#314]
Docker stops after few seconds when trying to use webRTC. #289 

`environment:
    - WEBRTC=True
    - FRESH_DATA=True`

This is the log. I have hidden my device mac.

`Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 584, in <module>

    wb.run()
  File "/app/wyze_bridge.py", line 49, in run
    self.get_webrtc()
  File "/app/wyze_bridge.py", line 401, in get_webrtc
    if wss := wyzecam.api.get_cam_webrtc(self.auth, cam.mac):
  File "/app/wyzecam/api.py", line 230, in get_cam_webrtc
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://webrtc.api.wyze.com/signaling/device/XXXXXXX?use_trickle=true
`

**Comment by mrlt8** [comment]
Unfortunately, some cams/firmware don't seem to support Webrtc yet and will result in a 404.
