### ISSUE TITLE
Problems with rtsp & rtmp

### ISSUE THREAD

**Issue by cbrightly** [mrlt8/docker-wyze-bridge#383]
Using the latest builds of Home Assistant (rpi4 64bit build) and core 2022.5.4 along with 1.4.4 of docker-wyze-bridge I get the following interspersed with normal messages in my logs, and the stream appears to cut out entirely at some points (while working okay other times):

```
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1372, in _path_importer_cache
KeyError: '/usr/local/lib/python3.10/site-packages'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/lib/python3.10/site.py", line 610, in main
    execsitecustomize()
  File "/usr/local/lib/python3.10/site.py", line 549, in execsitecustomize
    import sitecustomize
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1374, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1352, in _path_hooks
KeyboardInterrupt
```

Additionally, I am seeing a lot of "Output file #0 does not contain any stream"
```

Output file #0 does not contain any stream
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 5, in <module>
    import signal
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
```

Thanks as always for your assistance!

**Comment by mrlt8** [comment]
I believe it's coming from rtsp-simple-server killing the runon command, but will look into it further.

`Output file #0 does not contain any stream` is coming from ffmpeg when trying to take a snapshot because we're not giving it enough time to analyze the stream - this was done to speed up snapshots as it would sometimes taking over 40 seconds for a single image.
