### ISSUE TITLE
Python AttributeError for Filtering Cams

### ISSUE THREAD

**Issue by Webtron18** [mrlt8/docker-wyze-bridge#422]
I set this up for Portainer using the following compose file:
```
version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8889:8888 # HLS
        environment:
            - WYZE_EMAIL=# Replace with wyze email 
            - WYZE_PASSWORD=# Replace with wyze password
            - FILTER_NAMES=oldcam #This is the V1 cam im trying to filter out
            - FILTER_BLOCK=true
```

It looks like it works once I enter my auth code and then I get an AttributeError for the filtering cams:
```
🚀 STARTING DOCKER-WYZE-BRIDGE v1.5.4
2022/06/16 01:43:48 [WyzeBridge] 📚 Using 'user' from local cache...
2022/06/16 01:43:48 [WyzeBridge] 📚 Using 'cameras' from local cache...
2022/06/16 01:43:48 [WyzeBridge] 💔 WYZEC1 not supported
Traceback (most recent call last):
  File "/app/wyze_bridge.py", line 820, in <module>

    wb.run()
  File "/app/wyze_bridge.py", line 50, in run
    self.get_filtered_cams()
  File "/app/wyze_bridge.py", line 311, in get_filtered_cams
    cams.os.remove(cam)
AttributeError: 'list' object has no attribute 'os'
```

**Comment by mrlt8** [comment]
whoops, I see it! will push a fix!

btw, would you be willing to do some testing so we might be able to get the v1 supported?

**Comment by encg** [comment]
I had this error on v1.5.4 as well (fixed now with 1.6.0 - thanks!) and am willing to do some testing on my V1s.

**Comment by Webtron18** [comment]
Absolutely, I love helping out with this stuff. Just let me know what you need me to do.

**Comment by mrlt8** [comment]
Marking this issue as resolved.

@Webtron18, would appreciate it if you could test out the https://github.com/mrlt8/docker-wyze-bridge/tree/cam_v1 branch and report any errors you see in #57.
