### ISSUE TITLE
Wyze Doorbells lag behind by minutes, known issue?

### ISSUE THREAD

**Issue by kimrosebush** [mrlt8/docker-wyze-bridge#452]
Hi there, I'm experiencing this time delay issue with two newly installed Wyze Cam Doorbell WYZEDB3's firmware versions 4.25.1.060.

I'm currently pulling the streams using VLC and also attempting to record it towards my Synology NVR.

Timestamps in the video show the clock going at a slower rate and therefore the stream doesn't catch up. VLC also tends to show it's timestamp which sporattically goes forward and backwards a few seconds while it attempts to catch up.

I've launched my environment as follows:

```
docker run -d --restart always -e WYZE_EMAIL=x@x -e WYZE_PASSWORD=x -e WB_SHOW_VIDEO=True -e ROTATE_DOOR=True -e ENABLE_AUDIO=True -e FIX_FPS -p 5000:5000 -p 8888:8888 -p 8554:8554 mrlt8/wyze-bridge:latest
```

This launches version 1.6.7 currently, I have applied the FPS_FIX mentioned in #434, also mentioning #340 as this seems similar.

Logging is as follows:

```
* Serving Flask app 'frontend' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022/06/28 04:53:56 [WyzeBridge] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.6.7

2022/06/28 04:53:56 [WyzeBridge] 🔍 Could not find local cache for 'user'
2022/06/28 04:53:56 [WyzeBridge] 🔍 Could not find local cache for 'auth'
2022/06/28 04:53:56 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/06/28 04:53:56 [WyzeBridge]  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000 (Press CTRL+C to quit)
2022/06/28 04:53:57 [WyzeBridge] 💾 Saving 'auth' to local cache...
2022/06/28 04:53:57 [WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
2022/06/28 04:53:57 [WyzeBridge] 💾 Saving 'user' to local cache...
2022/06/28 04:53:57 [WyzeBridge] 🔍 Could not find local cache for 'cameras'
2022/06/28 04:53:57 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
2022/06/28 04:53:57 [WyzeBridge] 💾 Saving 'cameras' to local cache...
2022/06/28 04:53:57 [WyzeBridge] 
🎬 STARTING ALL 2 CAMERAS
2022/06/28 04:53:57 [WyzeBridge] Starting rtsp-simple-server v0.19.2
2022/06/28 04:53:57 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.140 (1/3)
2022/06/28 04:53:57 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Garage on 192.168.102.148 (1/3)
2022/06/28 04:53:59 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 87%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/28 04:53:59 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/28 04:53:59 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/28 04:54:00 [Garage] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 72%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/28 04:54:00 [Garage] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/28 04:54:00 [Garage] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/28 04:54:01 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/28 04:54:02 [RTSP][GARAGE] ✅ '/garage' stream is UP! (3/3)
2022/06/28 04:54:05 [RTSP][GARAGE] 📖 New client reading 
2022/06/28 04:54:05 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 04:55:24 [Front door] WARNING: FPS param mismatch (avRecv FPS=15)
2022/06/28 04:56:37 [RTSP][GARAGE] 📖 New client reading
```

I also am on a UniFi network, and have seen some sort of utilization issue on 2.4ghz mentioned in #241.

Any further debugging please let me know, I am eager to get this to work. Thanks in advance!

**Comment by mrlt8** [comment]
This seems similar to what @krystiancharubin was experiencing.

Does this only happen when the cam switches to night mode?

**Comment by kimrosebush** [comment]
> This seems similar to what @krystiancharubin was experiencing.
> 
> Does this only happen when the cam switches to night mode?

I've disabled night mode, though when it is enabled I do get the 15fps problem. When on "normal" day mode the time lag also occurs.

**Comment by krystiancharubin** [comment]
I also have a UniFi network and things still seem to be working fine.
Same firmware FW: 4.25.1.060 and the following settings.
```
NET_MODE: LAN
ROTATE_DOOR: "true"
RTSP_READTIMEOUT: 30
QUALITY: HD180
ENABLE_AUDIO: "true"
```

**Comment by kimrosebush** [comment]
> And the lag affecting both of the doorbells by a similar amount?
> 
> I wonder if we should just ignore any FPS from the camera and always use 20 fps for all doorbells..?
> 
> could you try running the [fps_drift](https://github.com/mrlt8/docker-wyze-bridge/tree/fps_drift) branch to see if that helps?

Hi there @mrlt8 thanks for getting back to me!

I have successfully compiled and am running the [fps_drift](https://github.com/mrlt8/docker-wyze-bridge/tree/fps_drift) branch. Unfortunately the time drift still occurs, I am getting about an hour delay on one camera where the other is only by 10 minutes. Writing this I have just noticed the camera with the hour delay catching itself up, however there's still a delay of a few minutes. The delay grows larger with the passage of time.

The same delay can be experienced on the web interface presented on port 5000 though I am primarily looking at them through RTSP on my Synology.

Here is the logs from the container:

```
 * Serving Flask app 'frontend' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022/06/28 22:16:56 [WyzeBridge] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.6.8

2022/06/28 22:16:56 [WyzeBridge] 🔍 Could not find local cache for 'user'
2022/06/28 22:16:56 [WyzeBridge] 🔍 Could not find local cache for 'auth'
2022/06/28 22:16:56 [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
2022/06/28 22:16:57 [WyzeBridge]  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000 (Press CTRL+C to quit)
2022/06/28 22:16:57 [WyzeBridge] 💾 Saving 'auth' to local cache...
2022/06/28 22:16:57 [WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
2022/06/28 22:16:57 [WyzeBridge] 💾 Saving 'user' to local cache...
2022/06/28 22:16:57 [WyzeBridge] 🔍 Could not find local cache for 'cameras'
2022/06/28 22:16:57 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
2022/06/28 22:16:58 [WyzeBridge] 💾 Saving 'cameras' to local cache...
2022/06/28 22:16:58 [WyzeBridge] 
🎬 STARTING ALL 2 CAMERAS
2022/06/28 22:16:58 [WyzeBridge] Starting rtsp-simple-server v0.19.2
2022/06/28 22:16:58 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.116 (1/3)
2022/06/28 22:16:58 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Garage on 192.168.102.148 (1/3)
2022/06/28 22:17:00 [Garage] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 83%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/28 22:17:00 [Garage] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/28 22:17:00 [Garage] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/28 22:17:00 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 90%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/28 22:17:00 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/28 22:17:00 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/28 22:17:02 [RTSP][GARAGE] ✅ '/garage' stream is UP! (3/3)
2022/06/28 22:17:03 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/28 22:17:03 [RTSP][GARAGE] 📖 New client reading 
2022/06/28 22:17:03 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 22:17:03 [RTSP][GARAGE] 📖 New client reading 
2022/06/28 22:17:03 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/28 22:17:03 [RTSP][GARAGE] 📕 Client stopped reading
2022/06/28 22:17:04 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 22:17:04 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 22:17:05 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/28 22:17:06 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 22:17:06 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/28 22:17:07 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/28 22:17:08 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/28 23:29:32 [Garage] WARNING: Frame not available yet
2022/06/28 23:29:33 [Garage] WARNING: Wrong resolution (frame_size=4)
2022/06/28 23:29:33 [Garage] Requesting frame_size=0 and bitrate=180
2022/06/29 01:01:38 [Front door] WARNING: Waiting for keyframe
2022/06/29 01:57:55 [Front door] WARNING: Error: -20016
2022/06/29 01:57:55 [Front door] WARNING: Audio pipe closed
2022/06/29 01:58:03 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/06/29 01:58:03 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 01:58:03 [Front door] AV_ER_REMOTE_TIMEOUT_DISCONNECT
2022/06/29 01:58:04 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.116 (1/3)
2022/06/29 01:58:06 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 100%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/29 01:58:06 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/29 01:58:06 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/29 01:58:08 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/29 01:58:21 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:02:56 [Front door] WARNING: Frame not available yet
2022/06/29 02:36:58 [Front door] WARNING: Waiting for keyframe
2022/06/29 02:37:16 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:37:17 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:37:18 [Front door] WARNING: Audio pipe closed
2022/06/29 02:37:19 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/06/29 02:37:19 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:37:20 [Front door] Stream did not receive a frame for over 30s
2022/06/29 02:37:20 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.116 (1/3)
2022/06/29 02:37:34 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 95%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/29 02:37:34 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/29 02:37:34 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
[h264 @ 0x55df8905a800] Missing reference picture, default is 0
[h264 @ 0x55df8905a800] decode_slice_header error
2022/06/29 02:37:36 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/29 02:37:38 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:38:10 [Front door] WARNING: Frame not available yet
2022/06/29 02:46:33 [Front door] WARNING: Audio pipe closed
2022/06/29 02:46:33 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:46:34 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/06/29 02:46:35 [Front door] Stream did not receive a frame for over 30s
2022/06/29 02:46:35 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.116 (1/3)
2022/06/29 02:46:44 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 93%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/29 02:46:44 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/29 02:46:44 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/29 02:46:47 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/29 02:46:49 [RTSP][FRONT-DOOR] 📖 New client reading 
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 73, in <module>
    import os
  File "/usr/local/lib/python3.10/os.py", line 27, in <module>
    import stat as st
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
KeyboardInterrupt
2022/06/29 02:46:50 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:46:50 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:46:51 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:46:52 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:46:53 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:46:53 [Front door] WARNING: Frame not available yet
2022/06/29 02:46:53 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:46:55 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 02:46:55 [RTSP][FRONT-DOOR] 📕 Client stopped reading
2022/06/29 02:47:11 [Front door] WARNING: Waiting for keyframe
2022/06/29 02:54:49 [Front door] WARNING: AV_ER_REMOTE_TIMEOUT_DISCONNECT
2022/06/29 02:54:49 [Front door] WARNING: Audio pipe closed
2022/06/29 02:54:512022/06/29 02:54:51 [RTSP][FRONT-DOOR] 📕 Client stopped reading
 [RTSP][FRONT-DOOR] ❌ '/front-door' stream is down
2022/06/29 02:54:52 [Front door] AV_ER_REMOTE_TIMEOUT_DISCONNECT
2022/06/29 02:54:52 [WyzeBridge] 🎉 Connecting to WyzeCam Doorbell - Front door on 192.168.102.116 (1/3)
2022/06/29 02:54:54 [Front door] 📡 Getting 180kb/s HD stream (20fps) via LAN mode (WiFi: 90%) FW: 4.25.1.060 🔒 (DTLS) (2/3)
2022/06/29 02:54:54 [Front door] 🔊 Audio Enabled - PCM > AAC/8,000Hz
2022/06/29 02:54:54 [Front door] WARNING: Skipping smaller frame at start of stream (frame_size=4)
2022/06/29 02:54:57 [RTSP][FRONT-DOOR] ✅ '/front-door' stream is UP! (3/3)
2022/06/29 02:55:09 [RTSP][FRONT-DOOR] 📖 New client reading 
2022/06/29 03:58:29 [Front door] WARNING: Wrong resolution (frame_size=4)
2022/06/29 03:58:29 [Front door] Requesting frame_size=0 and bitrate=180
2022/06/29 05:08:58 [Front door] WARNING: Waiting for keyframe
2022/06/29 07:41:58 [Garage] Requesting frame_size=0 and bitrate=180
2022/06/29 08:47:45 [Garage] Requesting frame_size=0 and bitrate=180
2022/06/29 09:17:56 [Front door] Requesting frame_size=0 and bitrate=180
2022/06/29 09:54:38 [RTSP][GARAGE] 📕 Client stopped reading
2022/06/29 09:54:39 [RTSP][GARAGE] 📖 New client reading 
2022/06/29 09:56:00 [Garage] WARNING: Waiting for keyframe
2022/06/29 10:26:29 [Front door] WARNING: Frame not available yet
2022/06/29 12:06:39 [RTSP][GARAGE] 📕 Client stopped reading
2022/06/29 12:06:40 [RTSP][GARAGE] 📖 New client reading 
2022/06/29 12:08:15 [RTSP][GARAGE] 📕 Client stopped reading
2022/06/29 12:08:16 [RTSP][GARAGE] 📖 New client reading 
2022/06/29 12:08:31 [Garage] Requesting frame_size=0 and bitrate=180
```

Thanks again!
@kimrosebush

**Comment by mrlt8** [comment]
Hmm, that is strange. Is it always the same doorbell that is further behind?

The RTSP stream should have the least delay, so that should be preferred for testing. Might also want to try another media player like VLC to see if the media player might be trying to buffer the stream.

Could you also see if there is any difference without rotation or audio enabled?

**Comment by kimrosebush** [comment]
> Hmm, that is strange. Is it always the same doorbell that is further behind?
> 
> The RTSP stream should have the least delay, so that should be preferred for testing. Might also want to try another media player like VLC to see if the media player might be trying to buffer the stream.
> 
> Could you also see if there is any difference without rotation or audio enabled?

I think you're onto something @mrlt8 with the ROTATE_DOOR option, I've turned this off and the drift has disappeared.

Any further debugging I can do for you let me know. For now it's good to have a up to date stream even though I can't rotate it on the Synology (yet?) :P

@kimrosebush

**Comment by kimrosebush** [comment]
It seems better now on a different host, with default launch options. I suspect the CPU in the Docker host I was using was not strong enough to handle the transcoding for rotation. I was hosting it off of a small NUC I task for lightweight tasks. It has 2 x Intel(R) Celeron(R) CPU J3060 @ 1.60GHz, thinking this may be the culprit.

It's happily chugging along on the other machine now and I can see the lag is disappeared on web UI.

Thanks for all the help, it was what I needed to get things working again!

**Comment by mrlt8** [comment]
Awesome! Glad you were able to get this resolved. I'll try to add a note re: rotation for future reference!

**Comment by cheme75** [comment]
FWIW, I’m running on 12 yr old gen 2 i5 cpus, originally a desktop 2450, currently a m450, both seem to handle it just fine - actually the first time I’ve gotten much use out of such old machines. I’ve switched some old machines to Linux for server purposes in the past but not many were older than 5-6 yrs. Anyway, the i5, even older probably has more capabilities than the nuc celerons. My scrypted/homebridge machine is a relatively weak dual core mobile pentium, a step up from the old atom cpus, moved it to lubuntu and it’s also running well since I stopped using as a digital frame to display a slideshow. Since I let it blank the screen now, it’s been running well.
