### ISSUE TITLE
Python error starting up BOA server

### ISSUE THREAD

**Issue by stevenwbuehler** [mrlt8/docker-wyze-bridge#504]
I get the following when passing the ENABLE_BOA option to a Docker version of wyze-bridge on a Raspberry Pi 4. (Configuration below message):

```
2022/08/11 17:09:12 [Printer Cam] starting boa server
Exception in thread PRINTER-CAM_BOA:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/wyze_bridge.py", line 1080, in camera_boa
    cmd = camera_cmd.get(timeout=interval)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 107, in get
    deadline = time.monotonic() + timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

Raspberry Pi 4B running Raspberry Pi OS 64-bit Bullseye

**Comment by mrlt8** [comment]
Thanks for the report. Looks like an issue with  `BOA_INTERVAL` will be pushing a fix for this!
