### ISSUE TITLE
fatal python error

### ISSUE THREAD

**Issue by tammeryousef1006** [mrlt8/docker-wyze-bridge#527]
2022/08/25 07:50:52 [WyzeBridge] 192.168.68.151 - - [25/Aug/2022 07:50:52] "GET /snapshot/officecam.jpg?1661413851550 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 5, in <module>
    import signal
  File "/usr/local/lib/python3.10/signal.py", line 3, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/local/lib/python3.10/enum.py", line 814, in <module>
    class Flag(Enum):
  File "/usr/local/lib/python3.10/enum.py", line 191, in __new__
    member_type, first_enum = metacls._get_mixins_(cls, bases)
  File "/usr/local/lib/python3.10/enum.py", line 621, in _get_mixins_
    member_type = _find_data_type(bases) or object
  File "/usr/local/lib/python3.10/enum.py", line 595, in _find_data_type
    if base is object:
KeyboardInterrupt
2022/08/25 07:50:52 [WyzeBridge] 192.168.68.151 - - [25/Aug/2022 07:50:52] "GET /snapshot/wyzev3.jpg?1661413851548 HTTP/1.1" 304 -
2022/08/25 07:50:52 [WyzeBridge] 192.168.68.151 - - [25/Aug/2022 07:50:52] "GET /snapshot/officecam.jpg?1661413851550 HTTP/1.1" 304 -
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 73, in <module>
    import os
  File "<frozen importlib._bootstrap>", line 1022, in _find_and_load
KeyboardInterrupt

**Comment by mrlt8** [comment]
You should be able to ignore this message. 
This error pops up every now and then when rtsp_event.py gets closed while it's loading which usually happens when an RTSP client disconnects too quickly.

**Comment by tammeryousef1006** [comment]
Many thanks for replying 🙂
