### ISSUE TITLE
Cannot start after latest update on HASS

### ISSUE THREAD

**Issue by Maksim-us** [mrlt8/docker-wyze-bridge#561]
Starts and then immediately stops. No error. The only thing in the logs:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/frontend.py", line 19, in <module>
    import wyze_bridge
  File "/app/wyze_bridge.py", line 388
    if env_bool("rtsp_fw") and rtsp_path := self.check_rtsp_fw(cam):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot use assignment expressions with expression
```

**Comment by mrlt8** [comment]
This should be fixed in v1.8.10.

**Comment by mrlt8** [comment]
May need to reload/refresh to show the update in HASS.

**Comment by mrlt8** [comment]
@Maksim-us were you able to get the latest version to work?

**Comment by Maksim-us** [comment]
Yes, had to restart HA a couple of times, but after a while it picked up
the available update and updated to the latest version. All good now.
Thanks!
