### ISSUE TITLE
stopping the cameras / can only join a child process

### ISSUE THREAD

**Issue by mjb83** [mrlt8/docker-wyze-bridge#620]
I updated home assistant (OS) the other day and I guess 1.91 docker wyze bridge came out as well, and since then I've had nothing but stability issues. Camera's are dropping or not showing anything seem to be stopping at the same time the logs show this:

2022/11/21 22:39:52 [Cam1] Stopping the cameras...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/app/wyzecam/tutk/tutk_ioctl_mux.py", line 289, in run
    raise tutk.TutkError(actual_len)
wyzecam.tutk.tutk.TutkError: AV_ER_CLIENT_EXIT
2022/11/21 22:39:53 [Cam1] can only join a child process
2022/11/21 22:39:53 [Cam2] IOTC_ER_DEVICE_OFFLINE

any ideas?

**Comment by mrlt8** [comment]
This is a known bug in v1.9.1 related to #619.

Still working on a fix, but you should be able to temporarily downgrade back to 1.9.0 using the "previous build" in the edge branch: https://github.com/mrlt8/edge-repo

**Comment by mjb83** [comment]
Ah, perfect thank you. I tried search and wasn't finding my exact errors. Previous build has all 4 of my cameras back up and running tyvm.

**Comment by mrlt8** [comment]
Hey @mjb83 could you try the dev branch in the edge repo to see if that helps?

**Comment by mjb83** [comment]
I just tried installing / starting dev branch and got the following error:

Failed to start add-on
Image mrlt8/wyze-bridge:dev does not exist for addon_38e363ab_docker-wyze-bridge-dev

**Comment by mrlt8** [comment]
hmm, could you try again? I was able to install the dev branch on my test HA.

**Comment by mjb83** [comment]
OK, uninstall/reinstall got it going.

Back up and running on the DEV branch now with 1.9.1... No issues so far. I'll leave it and post any logs if I crash again today.

FYI I'm piping through blue iris, if that matters at all. The logs I provide are obviously from the Wyze bridge in home assistant so I assume blue iris doesn't matter.

2022/11/22 10:08:26 [WyzeBridge] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.9.1
2022/11/22 10:08:26 [WyzeBridge] 🏠 Home Assistant Mode
2022/11/22 10:08:26 [WyzeBridge] 📚 Using 'user' from local cache...
2022/11/22 10:08:26 [WyzeBridge] ♻️ Refreshing camera data for thumbnails
2022/11/22 10:08:26 [WyzeBridge] 📚 Using 'auth' from local cache...
2022/11/22 10:08:26 [WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
2022/11/22 10:08:26 [WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://x.x.x.x:5000
2022/11/22 10:08:26 [WyzeBridge] Press CTRL+C to quit
2022/11/22 10:08:27 [WyzeBridge] 💾 Saving 'cameras' to local cache...
2022/11/22 10:08:27 [WyzeBridge] 
🎬 STARTING ALL 4 CAMERAS

**Comment by mjb83** [comment]
Seems stable, from a client perspective anyway. I have one feed going to my Blueiris recording software and then a tablet on the main floor with TinyCam Pro to watch the front / back door and the kid's rooms. Both BI and TC feeds have been up solid since the update yesterday morning. Nothing I can see in the logs for either is showing any signs of dropping.

I am seeing quite a lot of 'client stopped reading' and 'new client reading' in the docker Wyze bridge logs tho:

2022/11/23 08:06:24 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:06:24 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:06:24 [RTSP][CAM3] 📕 Client stopped reading
2022/11/23 08:06:24 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:06:24 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:06:24 [RTSP][CAM3] 📖 New client reading 
2022/11/23 08:06:27 [CAM4] 📡 Getting 120kb/s HD stream (H264/10fps) via LAN mode (WiFi: 100%) FW: 4.9.6.156 (2/3)
2022/11/23 08:06:27 [RTSP][CAM4] ✅ '/CAM4' stream is UP! (3/3)
2022/11/23 08:06:29 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:06:38 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:28:35 [RTSP][CAM3] 📕 Client stopped reading
2022/11/23 08:28:37 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:28:40 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:28:48 [RTSP][CAM3] 📖 New client reading 
2022/11/23 08:28:48 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:28:55 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:28:57 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 08:28:59 [RTSP][CAM3] 📕 Client stopped reading
2022/11/23 08:29:19 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:29:54 [RTSP][CAM3] 📖 New client reading 
2022/11/23 08:29:54 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:29:54 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:29:55 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:30:30 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:39:18 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:39:18 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 08:39:19 [RTSP][CAM3] 📕 Client stopped reading
2022/11/23 08:39:19 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:39:19 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:39:19 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:39:20 [RTSP][CAM3] 📖 New client reading 
2022/11/23 08:39:21 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:41:59 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:41:59 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:41:59 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 08:41:59 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:42:01 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:42:01 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:55:39 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 08:55:40 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:55:40 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:55:42 [RTSP][CAM4] 📖 New client reading 
2022/11/23 08:57:59 [RTSP][CAM1] 📕 Client stopped reading
2022/11/23 08:57:59 [RTSP][CAM2] 📕 Client stopped reading
2022/11/23 08:58:00 [RTSP][CAM1] 📖 New client reading 
2022/11/23 08:58:01 [RTSP][CAM2] 📖 New client reading 
2022/11/23 08:58:01 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 08:58:03 [RTSP][CAM4] 📖 New client reading 
2022/11/23 09:06:05 [RTSP][CAM4] ❌ '/CAM4' stream is down
2022/11/23 09:06:05 [RTSP][CAM4] 📕 Client stopped reading
2022/11/23 09:06:05 [RTSP][CAM4] 📕 Client stopped reading

**Comment by mrlt8** [comment]
hmm, could that be from Blueiris?

**Comment by mjb83** [comment]
I don't think so, I'm not seeing any disconnection-type events in the logs there.

**Comment by mjb83** [comment]
Moved back to prod, looks good so far. Note I'm still seeing the development server message on boot.

2022/11/24 12:48:44 [WyzeBridge] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.9.2
2022/11/24 12:48:44 [WyzeBridge] 🏠 Home Assistant Mode
2022/11/24 12:48:44 [WyzeBridge] 📚 Using 'user' from local cache...
2022/11/24 12:48:44 [WyzeBridge] 📚 Using 'cameras' from local cache...
2022/11/24 12:48:44 [WyzeBridge] 
🎬 STARTING ALL 4 CAMERAS
 * Serving Flask app 'frontend'
 * Debug mode: off
2022/11/24 12:48:44 [WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://x.x.x.x:5000
2022/11/24 12:48:44 [WyzeBridge] Press CTRL+C to quit
2022/11/24 12:48:44 [WyzeBridge] Starting rtsp-simple-server v0.20.2

**Comment by mrlt8** [comment]
That's coming from Flask and can be ignored for now.
