### ISSUE TITLE
V1.10.0 Addon will not start 

### ISSUE THREAD

**Issue by tbrausch** [mrlt8/docker-wyze-bridge#638]
I get the following errors in the log when trying to start V1.10.0 as a HA Addon:

```
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/frontend.py", line 27, in <module>
    pw = generate_password_hash(os.getenv("WEB_PASSWORD", os.getenv("WYZE_PASSWORD")))
  File "/usr/local/lib/python3.10/site-packages/werkzeug/security.py", line 88, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/usr/local/lib/python3.10/site-packages/werkzeug/security.py", line 36, in _hash_internal
    password = password.encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by delzear** [comment]
Same thing here

**Comment by mrlt8** [comment]
Thanks for the heads up! I temporarily disabled the web auth feature for HA in v1.10.1 until I can work out a fix!
