### ISSUE TITLE
Missing credentials: WYZE_EMAIL WYZE_PASSWORD after update

### ISSUE THREAD

**Issue by JerrettDavis** [mrlt8/docker-wyze-bridge#683]
After installing the latest update (1.11.2) in Home Assistant, the add-on no longer starts up. When I look at the log, I receive the following error: `Missing credentials: WYZE_EMAIL WYZE_PASSWORD`, but looking at both the GUI and yaml, the entries for both email and password are definitely present and correct.

![image](https://user-images.githubusercontent.com/2610199/213763243-d4a4956e-7481-4559-b290-bceb32c463c8.png)

![image](https://user-images.githubusercontent.com/2610199/213763374-c5063886-37aa-4f91-8179-9751cead4615.png)

![image](https://user-images.githubusercontent.com/2610199/213763542-4ec4f8b9-20a1-4d68-a54e-84831226e15d.png)

**Comment by JerrettDavis** [comment]
From looking at the latest update, it seems related to the following change:

https://github.com/mrlt8/docker-wyze-bridge/compare/v1.11.1...v1.11.2#diff-fbb05ddf8cefaa061d4a80f3c653996389c522499a248721af7ec928c233029eR1471-R1483

**Comment by joshsanderfer** [comment]
Just ran a partial restore and they're back up.

**Comment by M1K3SD1** [comment]
Just upgraded, getting "Missing credentials: WYZE_EMAIL WYZE_PASSWORD" when attempting to start. The credentials haven't changed and are correctly saved.

**Comment by bleem313** [comment]
Having the same issue with the latest release. Was working in 1.11.1

Here is my config:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/10550155/213781337-78197496-3a06-4c51-bca7-aa8385b63d2f.png">

**Comment by Hexis858** [comment]
I have the same issue and restoring to the previous v1.11.1 fix it.

**FYI**

Reinstalling the add-on or changing the Wyze password did not fix the issue.

The log only shows:
```
Missing credentials: WYZE_EMAIL WYZE_PASSWORD
```

In version 1.11.1, the log would start with:
```
2023/01/20 15:37:14 [WyzeBridge] STARTING DOCKER-WYZE-BRIDGE
2023/01/20 15:37:14 [WyzeBridge] Home Assistant Mode
etc...
```

Thanks so mush for building this Wyze Bridge :)

**Comment by truejim** [comment]
I am also getting the same the same error in my logs.

- I use 2-factor
-  Home Assistant 2023.1.6
- Supervisor 2022.12.1
- Operating System 9.4
- Virtual server on proxmox

**Comment by Truepix** [comment]
Same thing here  I'm waiting for a fix or I'm installing the old version (1.11.1) ...

**Comment by mrlt8** [comment]
Sorry about that. This should be fixed in v1.11.3.

**Comment by M1K3SD1** [comment]
Confirmed as fixed in 1.11.3.
Thank you so much for the fix and the add-on, it's awesome!

P.S, I noticed the following error when starting up, although everything seems to be working, so not sure of the significance.
Please let me know if you want me to submit an issue for this.

`2023/01/20 17:34:35 [RTSP][FRONTYARD] ✅ '/frontyard' stream is UP! (3/3)
2023/01/20 17:34:36 [RTSP][BACKYARD] ✅ '/backyard' stream is UP! (3/3)
Traceback (most recent call last):
  File "/app/rtsp_event.py", line 5, in <module>
    import signal
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site.py", line 617, in <module>
    main()
  File "/usr/local/lib/python3.10/site.py", line 604, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/lib/python3.10/site.py", line 387, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/lib/python3.10/site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
KeyboardInterrupt
2023/01/20 17:34:40 [RTSP][FRONTYARD] 📖 New client reading 
2023/01/20 17:34:40 [RTSP][BACKYARD] 📖 New client reading `

**Comment by Truepix** [comment]
Nice Work and reallly fast cheer!!!

**Comment by JerrettDavis** [comment]
Confirmed working with 1.11.3 Good work!
