### ISSUE TITLE
MQTT take_photo doesnt capture image and prevents further MQTT responses

### ISSUE THREAD

**Issue by linuxguygary** [mrlt8/docker-wyze-bridge#712]
I am unable to capture a snapshot via mqtt.  I am successfully using mqtt to check status and set options, however attempting to capture a snapshot with topic:  "wyzebridge/mono-x/cmd"   and a message of "take_photo"  does not return a response to the mqtt topic (like the other commands do).  Snapshots do work from the web interface and also from the direct  /snapshot/mono-x.jpg url, ruling out permission and filesystem issues.
 Once the take_photo command has been sent the mqtt responses stop until I stop the stream via the web interface and restart it. 
Using Home Assistant 2023.2.3
Supervisor 2023.01.1
Frontend 20230202.0 - latest 

and latest version of the bridge 1.11.7 

**From the log, here's a valid response from a different command:**
2023/02/08 11:24:22 [Mono X] [CONTROL] Response: {'cmd': 'get_night_vision', 'status': 'success', 'response': 3}

**Here's the attempted take_photo command and the resulting exception.**
```

2023/02/08 11:25:13 [Mono X] [CONTROL] Request: take_photo via MQTT!
2023/02/08 11:25:14 [Mono X] [CONTROL] Response: {'cmd': 'take_photo', 'status': 'success', 'response': b'\x01'}
Exception in thread Thread-54 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/app/wyze_bridge.py", line 1241, in _on_message
    client.publish(msg.topic, json.dumps(resp))
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by mrlt8** [comment]
Thanks! We need to return an integer instead of byte there.

Also, this won't take a snapshot on the bridge, but will send a command to the camera to take a photo on the SD card ( /media/mmc/photo/YYYYMMDD/YYYYMMDD_HH_MM_SS.jpg).
