### ISSUE TITLE
MQTT missing required key data['topic'] for home assistant autodiscovery

### ISSUE THREAD

**Issue by bdashrad** [mrlt8/docker-wyze-bridge#751]
Since v2 the mqtt payload is missing a required key `data['topic']` for home assistant autodiscovery to work. Confirmed this key is included in v1.11.10.

Private data removed from log entry from Home Assistant MQTT Integration

```
2023-03-22 11:33:41.653 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_camera_mqtt': ({'unique_id': 'WYZE1234567890AB', 'name': 'Wyze Cam Home', 'json_attributes_topic': 'wyzebridge/home/attributes', 'availability_topic': 'wyzebridge/home/state', 'icon': 'mdi:image', 'device': {'connections': [['mac', '1234567890AB']], 'identifiers': '1234567890AB', 'manufacturer': 'Wyze', 'model': 'WYZEC1-JZ', 'sw_version': '4.9.9.1574', 'via_device': 'docker-wyze-bridge'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/components/mqtt/mixins.py", line 316, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
  File "/usr/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['topic']
```

**Comment by mrlt8** [comment]
Thank you! Can confirm the issue with autodiscovery. 
Trying to see if we might be able to set the camera stream over mqtt at the same time.

**Comment by ntbritton** [comment]
I am also seeing the same problem.    Hers is a snipit from my log:

`Exception in async_discover when dispatching 'mqtt_discovery_new_camera_mqtt': ({'unique_id': 'WYZE2uniqid', 'name': 'Wyze Cam basement ', 'json_attributes_topic': 'wyzebridge/basement/attributes', 'availability_topic': 'wyzebridge/basement/state', 'icon': 'mdi:image', 'device': {'connections': [['mac', '##########']], 'identifiers': '###########', 'manufacturer': 'Wyze', 'model': 'WYZEC1-JZ', 'sw_version': '4.9.8.1002', 'via_device': 'docker-wyze-bridge'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 316, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: required key not provided @ data['topic']`

Here is my wyze-bridge config for mqtt:
![image](https://user-images.githubusercontent.com/51688954/228844470-bfd2bf95-3409-41a1-8b68-2f341252e56b.png)

**Comment by Mincka** [comment]
It looks like `MQTT_TOPIC` is never used in the code in [mqtt.py](https://github.com/mrlt8/docker-wyze-bridge/blob/main/app/wyzebridge/mqtt.py).

**Comment by mrlt8** [comment]
Made some updates to the MQTT auto-discovery in the dev branch:

https://github.com/mrlt8/edge-repo
