### ISSUE TITLE
WebUi. Will not lunch 

### ISSUE THREAD

**Issue by Rolo1990** [mrlt8/docker-wyze-bridge#752]
I’m using my synoloy nas with docker
I added the correct ports, and  my web UI will not load. ??? Any help

**Comment by mrlt8** [comment]
Anything in the logs? Are the individual streams working?

**Comment by FrankFromHR** [comment]
I'm having a similar problem.

It seems like it's having issues connecting to the Wyze API but it also seems like the python is crashing when it gets a GET request. 

It also doesn't seem to want to accept any of the debug or the API environment variables. 

Error log from the docker container.

`🚀 STARTING DOCKER-WYZE-BRIDGE v2.0.1

22:38:03 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:03 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
22:38:03 [INFO][WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.112.2:5000
22:38:03 [INFO][WyzeBridge] Press CTRL+C to quit
22:38:03 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:04 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:04 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:04 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"4e1c6bfb-7ba4-4dd1-813b-c1cfee666303","errorCode":1000}
22:38:04 [INFO][WyzeBridge] 🔍 Could not find local cache for 'user'
22:38:04 [INFO][WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
22:38:04 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:04 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
22:38:04 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:04 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:04 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:04 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"3590defc-7990-477d-ad62-359aa070715d","errorCode":1000}
22:38:04 [INFO][WyzeBridge] 🔍 Could not find local cache for 'cameras'
22:38:04 [INFO][WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
22:38:04 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:04 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
22:38:04 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:04 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:04 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:04 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"8a0efa62-b071-4106-8452-ede9743ff136","errorCode":1000}
22:38:04 [INFO][WyzeBridge] starting rtsp-simple-server v0.21.6
22:38:04 [INFO][WyzeBridge] Stopping 0 streams
22:38:04 [INFO][WyzeBridge] Stopping rtsp-simple-server...
22:38:04 [INFO][WyzeBridge] 👋 goodbye!
22:38:15 [INFO][WyzeBridge] 🔍 Could not find local cache for 'cameras'
22:38:15 [INFO][WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
22:38:15 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:15 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
22:38:15 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:15 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:15 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:15 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"f662058d-41b9-48af-b2a6-2ef97c8c42a8","errorCode":1000}
22:38:15 [ERROR][WyzeBridge] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/frontend.py", line 65, in index
    cam_data=web_ui.all_cams(wb.streams, wb.api.total_cams, host),
                                         ^^^^^^^^^^^^^^^^^
  File "/app/wyzebridge/wyze_api.py", line 89, in total_cams
    return 0 if self.mfa_req else len(self.get_cameras())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
22:38:15 [INFO][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:15] "GET / HTTP/1.1" 500 -
22:38:19 [INFO][WyzeBridge] 🔍 Could not find local cache for 'cameras'
22:38:19 [INFO][WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
22:38:19 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:19 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
22:38:19 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:19 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:19 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:19 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"daa2a47b-2fd6-4958-badf-11bb0b61d962","errorCode":1000}
22:38:19 [ERROR][WyzeBridge] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/frontend.py", line 65, in index
    cam_data=web_ui.all_cams(wb.streams, wb.api.total_cams, host),
                                         ^^^^^^^^^^^^^^^^^
  File "/app/wyzebridge/wyze_api.py", line 89, in total_cams
    return 0 if self.mfa_req else len(self.get_cameras())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
22:38:19 [INFO][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:19] "GET / HTTP/1.1" 500 -
22:38:23 [ERROR][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:23] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03c±v6\x87b8Üé\x894ð\x93M')
22:38:23 [INFO][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:23] "üc±v6b8Üé4ðM" 400 -
22:38:23 [ERROR][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:23] code 400, message Bad request version ('\x00\x14\x00\x12\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x02\x01\x00')
22:38:23 [INFO][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:23] "ü]¬ËÔWSÜ½¿Yµ+\Z:O5¼KUû;É$Dè© 8h¥ÞÚ­£v]U=?Û§+m÷'UDÿ(Ô À+À/À,À0Ì©Ì¨ÀÀ/5ÿ+JJ
                                                                                                                                                                               
                                                                                                                                                                                         
" 400 -                                                                                                                                                                http/1.1
22:38:27 [INFO][WyzeBridge] 🔍 Could not find local cache for 'cameras'
22:38:27 [INFO][WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
22:38:27 [INFO][WyzeBridge] 🔍 Could not find local cache for 'auth'
22:38:27 [INFO][WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
22:38:27 [DEBUG][WyzeBridge] Starting new HTTPS connection (1): auth-prod.api.wyze.com:443
22:38:28 [DEBUG][WyzeBridge] https://auth-prod.api.wyze.com:443 "POST /user/login HTTP/1.1" 400 None
22:38:28 [ERROR][WyzeBridge] ⚠️ 400 Client Error: Bad Request for url: https://auth-prod.api.wyze.com/user/login
22:38:28 [WARNING][WyzeBridge] {"description":"Invalid User Name or Password.","requestId":"c2aa5617-4fda-479f-9d78-3f0bd398495b","errorCode":1000}
22:38:28 [ERROR][WyzeBridge] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_httpauth.py", line 172, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/frontend.py", line 65, in index
    cam_data=web_ui.all_cams(wb.streams, wb.api.total_cams, host),
                                         ^^^^^^^^^^^^^^^^^
  File "/app/wyzebridge/wyze_api.py", line 89, in total_cams
    return 0 if self.mfa_req else len(self.get_cameras())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
22:38:28 [INFO][WyzeBridge] 192.168.1.199 - - [29/Mar/2023 22:38:28] "GET / HTTP/1.1" 500 -`



docker-compose.yml

`version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:latest
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 8889:8889 #WebRTC
            - 8189:8189/udp # WebRTC/ICE
            - 5000:5000 # WEB-UI
        environment:
            # [REQUIRED] Fill the following two lines:
            - WYZE_EMAIL=AnEmail@address.com 
            - WYZE_PASSWORD=SomePassword
            - DEBUG_LEVEL=debug
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
`

**Comment by FrankFromHR** [comment]
Wow it formatted that like crap, I copied the compose file from the website, and only added DEBUG_LEVEL and email and password.

**Comment by mrlt8** [comment]
Can you log into https://auth.wyze.com/login?
It's probably the rate-limiting which seems to return "Invalid User Name or Password" even though the credentials are correct.

**Comment by FrankFromHR** [comment]
Yeah I’m able to login without any issues.

**Comment by mrlt8** [comment]
Any special characters in the credentials? https://github.com/mrlt8/docker-wyze-bridge#special-characters

**Comment by FrankFromHR** [comment]
Yeah, I’ve tried escaping it and using double quotes, doesn’t seem to resolve anything.

**Comment by FrankFromHR** [comment]
I changed my password to remove the # in it and it seems to be working correctly now, I wonder if it might work better if we stored the password as a docker secret?

**Comment by mrlt8** [comment]
We could, but I believe docker secrets would still have the same issue with special characters?

I eventually want to add an alternate method to authenticate using the WebUI so we don't have to store the credentials and just use the tokens.

**Comment by chrisferagotti** [comment]
I've made sure my password is free of special characters (entirely alphanumeric, which was a nuisance, since the web UI won't let you, and you have to use the phone app entirely to reset/set it) and I can login to https://auth.wyze.com/login fine, but I'm still just getting "Invalid User Name or Password."

**Comment by FrankFromHR** [comment]
> 

Correct email address and double-checked the password? Mine isn't entirely alphanumeric just removed the special characters that Bash doesn't like.

**Comment by chrisferagotti** [comment]
Just about to say something like "yes, of course I did", then decided to
look back over it again.... I had tried it so many times that the last time
(with the proper alphanumeric password) I had mistyped my email address. 🙄

Looks like it's connecting now. Thank you for the reply!

**Comment by Chukkles84** [comment]
I cant reach the web ui I installed using portainer her is log it appears to be working correctly??

🚀 STARTING DOCKER-WYZE-BRIDGE v2.1.7
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.16.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Front Porch Cam [WYZE_CAKP2JFUS]
[WyzeBridge] starting MediaMTX v0.23.2
[WyzeBridge] 🎬 1 stream enabled

**Comment by mrlt8** [comment]
You should be able to access the server on `http://<ip.address.of.portainer>:5000/` with the default config, unless you had to change the port because it was already being used.

**Comment by dumb-questions23** [comment]
Hi

I'm having an issue changing the port of the webui.
I'm running portainer on my synology, which means the port 5000 is already in use by the DSM.

Obviosly, i can see the following on the logs of the container:
"Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port."

I've modified the docker compose file with the following settings:
wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
     - 1935:1935 # RTMP
     - 8554:8554 # RTSP
     - 8888:8888 # HLS
     - 8889:8889 #WebRTC
     - 8189:8189/udp # WebRTC/ICE
     - 5000:8890 # WEB-UI
    network_mode: host 
    environment:
            # [REQUIRED] Fill the following two lines:
     - WYZE_EMAIL= Email
     - WYZE_PASSWORD= Password
     # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
     # - WB_IP=192.168.1.122

Is there another environment variable i need to add? o (BTW, I've already tried using the ports like 8890:5000 and still have the same result, I always forget which one is which on that order)

Thanks for your help and sorry for the dumb question.

**Comment by mrlt8** [comment]
Second port is internal, so you need you need to use `8890:5000`.

I think `network_mode: host` might be the issue since it will open all ports which is probably what is causing the conflict.
