### ISSUE TITLE
Camera streams and snapshots no longer work after 2.3.5 with any Wyze cameras

### ISSUE THREAD

**Issue by ZacTyAdams** [mrlt8/docker-wyze-bridge#902]
Bridge is able to query api for list of cameras, but when connecting for a snapshot or stream, the log shows:
IOTC_ER_TIMEOUT

[WyzeBridge] ⏰ Timed out connecting to Living Room Cam.
[WyzeBridge] ⏰ Timed out connecting to Backyard Camera.

Have tested against versions 2.3.5 -> 2.3.8

**Comment by mrlt8** [comment]
Do you have the camera data cached? Can you run the container with FRESH_DATA or clear the data from the webUI using the `/restart/all` endpoint?

**Comment by ZacTyAdams** [comment]
It looks like it, I still have snapshots showing on the cameras from over a week ago. The restart does not seem to work anymore either, I’m getting "Restart all - The string did not match the expected pattern.” For both "clear cache and reconnect" and "connection to cameras"

**Comment by ZacTyAdams** [comment]
Just an update, I noticed this error in the logs when trying a restart and clear cache:
`[2023-07-17 14:19:33,382] ERROR in app: Exception on /restart/all [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/frontend.py", line 227, in restart_bridge
    wb.run(fresh_data=True)
  File "/app/wyze_bridge.py", line 36, in run
    self.streams.monitor_streams(self.rtsp.health_check)
  File "/app/wyzebridge/stream.py", line 98, in monitor_streams
    self.thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 952, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once`

**Comment by mrlt8** [comment]
Can you post the version you're using when getting that error?

**Comment by ZacTyAdams** [comment]
This is tested against 2.3.5+ with the error message there being from 2.3.10.

**Comment by ZacTyAdams** [comment]
Perfect thank you @mrlt8, I'll test again with the next release and the cameras on a new router as well.

**Comment by ZacTyAdams** [comment]
Yeah, no change here. I've changed routers in the home and removed then readded the camera to my Wyze app but still getting that timeout issue. 

```
[WyzeBridge] [+] Adding Living Room Cam [HL_PAN2]
[WyzeBridge] [+] Adding Backyard Camera [HL_PAN2]
[WyzeBridge] starting MediaMTX 0.23.8
[WyzeBridge] 🎬 3 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam Pan - Wyze Cam Pan on 192.168.1.23
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Living Room Cam on 192.168.1.104
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Backyard Camera on 192.168.1.200
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET / HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /static/site.css HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /static/loading.svg HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/living-room-cam.jpg HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/backyard-camera.jpg HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /static/site.js HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/living-room-cam.jpg HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/backyard-camera.jpg HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/living-room-cam.jpg HTTP/1.1" 304 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:01] "GET /img/backyard-camera.jpg HTTP/1.1" 304 -
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:13] "GET /img/wyze-cam-pan.jpg HTTP/1.1" 307 -
[WyzeBridge] ⏰ Timed out connecting to Wyze Cam Pan.
[WyzeBridge] ⏰ Timed out connecting to Living Room Cam.
[WyzeBridge] ⏰ Timed out connecting to Backyard Camera.
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:28] "GET /img/wyze-cam-pan.jpg HTTP/1.1" 307 -
[WyzeBridge] 🎉 Connecting to WyzeCam Pan - Wyze Cam Pan on 192.168.1.23
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Living Room Cam on 192.168.1.104
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Backyard Camera on 192.168.1.200
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:31] "GET /img/loading.svg HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:31] "GET /img/loading.svg HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:43] "GET /snapshot/living-room-cam.jpg?1689871591703= HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:43] "GET /snapshot/backyard-camera.jpg?1689871591705= HTTP/1.1" 307 -
[WyzeBridge] Stopping 3 streams
[WyzeBridge] Stopping MediaMTX...
ice ERROR: 2023/07/20 11:46:47 Failed to read UDP packet: read udp [::]:8189: use of closed network connection
[WyzeBridge] Stream monitoring stopped
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] 🎉 Connecting to WyzeCam Pan - Wyze Cam Pan on 192.168.1.23
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:59] "GET /snapshot/living-room-cam.jpg?1689871591703= HTTP/1.1" 307 -
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:59] "GET /img/wyze-cam-pan.jpg HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:59] "GET /img/wyze-cam-pan.jpg HTTP/1.1" 307 -
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:46:59] "GET /snapshot/backyard-camera.jpg?1689871591705= HTTP/1.1" 307 -
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Office Cam [WYZECP1_JEF]
[WyzeBridge] [+] Adding Living Room Cam [HL_PAN2]
[WyzeBridge] [+] Adding Backyard Camera [HL_PAN2]
[WyzeBridge] starting MediaMTX 0.23.8
[WyzeBridge] 🎬 4 streams enabled
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Living Room Cam on 192.168.1.104
[WyzeBridge] 🎉 Connecting to WyzeCam Pan V2 - Backyard Camera on 192.168.1.200
[WyzeBridge] 🎉 Connecting to WyzeCam Pan - Office Cam on 192.168.1.23
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:47:01] "GET /img/loading.svg HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:47:01] "GET /img/loading.svg HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:47:16] "GET /snapshot/backyard-camera.jpg?1689871621706= HTTP/1.1" 307 -
[WyzeBridge] 172.30.32.2 - - [20/Jul/2023 11:47:16] "GET /snapshot/living-room-cam.jpg?1689871621703= HTTP/1.1" 307 -
[WyzeBridge] ⏰ Timed out connecting to Wyze Cam Pan.
[office-cam] [-13] IOTC_ER_TIMEOUT
[living-room-cam] [-13] IOTC_ER_TIMEOUT
[backyard-camera] [-13] IOTC_ER_TIMEOUT
```

**Comment by DrDavy** [comment]
@ZacTyAdams I think we may have different issues with similar symptoms, my container wont even stay up :)
I have an older docker engine it seems anyways so I will probably try to update it and see if I get further

**Comment by ZacTyAdams** [comment]
@DrDavy Yeah this issue from the beginning seems to be something with the Wyze API. The restart and clear cache was one of the roadblocks though.
