### ISSUE TITLE
v2.3.9 errors

### ISSUE THREAD

**Issue by lviciedo** [mrlt8/docker-wyze-bridge#906]
[WyzeBridge] 🏠 Home Assistant Mode
🚀 DOCKER-WYZE-BRIDGE v2.3.9 
 * Serving Flask app 'frontend'
 * Debug mode: off
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.30.33.6:5000
    self.run()
[WyzeBridge] Press CTRL+C to quit
  File "/app/wyze_bridge.py", line 31, in run
    self.api.login(fresh_data=fresh_data)
  File "/app/wyzebridge/wyze_api.py", line 33, in wrapper
    if not (data := pickle.load(pkl_f)):
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 785, in __setstate__
    _object_setattr(self, '__pydantic_fields_set__', state['__pydantic_fields_set__']

**Comment by lviciedo** [comment]
All set
