### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by mpenda** [mrlt8/docker-wyze-bridge#909]
Just started today...docker shows it running, but I can't connect via any of the ports. Docker is running on a linux box.  Other containers are normal. The logs are as follows:🚀 DOCKER-WYZE-BRIDGE v2.3.9 
[WyzeBridge] ♻️ Clearing local cache...
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 93, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 235, in locate_app
    return find_best_app(module)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 63, in find_best_app
    app = app_factory()
          ^^^^^^^^^^^^^
  File "/app/frontend.py", line 38, in create_app
    wb.start()
  File "/usr/local/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by mrlt8** [comment]
Hi, was this an upgrade? There was an issue when upgrading to v2.3.9. Could you try updating to the latest v2.3.10 build?

**Comment by mpenda** [comment]
My apologies. The copy of the logs was indeed 2.3.9.  I had already pulled 2.3.10 and it does exactly the same thing.

**Comment by mrlt8** [comment]
Thanks for the info. Are you on a 32bit OS? It seems like this is probably related to the bullseye->bookworm change for the base image.

Any chance you can update [libseccomp](https://github.com/mrlt8/docker-wyze-bridge/wiki/Raspberry-Pi-(armv7-and-arm64)#libseccomp2) and docker on your host?

**Comment by mpenda** [comment]
Here's my OS: Pop!_OS 20.04 LTS (GNU/Linux 5.13.0-7614-generic x86_64)

I don't know how (yet) to update those, but I will certainly dig into it!

**Comment by mpenda** [comment]
I felt like I was in a horror movie, peeking behind that door to see what's there. I was WOEFULLY behind on updates so I did that, and among that list was docker and libseccomp2 (at least). 
After the updates, its working perfectly. Thank you for the guidance!
