### ISSUE TITLE
My wyze cameras have been unavailable for about a week now.

### ISSUE THREAD

**Issue by gleep52** [mrlt8/docker-wyze-bridge#942]
I just realized they were actually down in only wyzebridge - they work from the wyze app still.  

My log file looks like this:

`wyzecam.tutk.tutk.TutkError: AV_ER_CLIENT_EXIT
[back-garage] [CONTROL] AV_ER_CLIENT_EXIT
[back-garage] Stream did not receive a frame for over 15s
Exception in thread Thread-89:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/app/wyzecam/tutk/tutk_ioctl_mux.py", line 288, in run
    raise tutk.TutkError(actual_len)
wyzecam.tutk.tutk.TutkError: AV_ER_CLIENT_EXIT
[ravine] [CONTROL] AV_ER_CLIENT_EXIT
[ravine] [-20021] AV_ER_SENDIOCTRL_ALREADY_CALLED
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:46:38] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:46:38] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Garage on 192.168.3.142
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:46:38] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:46:38] "GET /static/notavailable.svg HTTP/1.1" 304 -
[back-garage] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 81%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[back-garage] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[back-garage] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Pool on 192.168.3.213
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Ravine on 192.168.3.250
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Wyze5 on 192.168.3.48
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Garage on 192.168.3.142
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/garage-2.jpg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/pool.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/ravine.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/wyze5.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/garage-2.jpg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/ravine.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/pool.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /img/wyze5.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[wyze5] 📡 Getting 180kb/s HD stream (H264/30fps) via LAN mode (WiFi: 71%) FW: 4.36.9.139 🔒 (DTLS) (2/3)
[pool] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 99%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[wyze5] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[pool] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[wyze5] FFMPEG stopped
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:23] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:23] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:23] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:47:23] "GET /static/notavailable.svg HTTP/1.1" 304 -
[ravine] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 98%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[ravine] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[pool] FFMPEG stopped
[back-garage] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 89%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
Exception in thread Thread-106:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/app/wyzecam/tutk/tutk_ioctl_mux.py", line 288, in run
    raise tutk.TutkError(actual_len)
wyzecam.tutk.tutk.TutkError: AV_ER_CLIENT_EXIT
[ravine] [CONTROL] AV_ER_CLIENT_EXIT
[ravine] Stream did not receive a frame for over 15s
[back-garage] FFMPEG stopped
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Ravine on 192.168.3.250
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Wyze5 on 192.168.3.48
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Pool on 192.168.3.213
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/pool.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/garage-2.jpg HTTP/1.1" 304 -
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Garage on 192.168.3.142
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/ravine.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/garage-2.jpg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/pool.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/ravine.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /img/back-garage.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:20] "GET /static/notavailable.svg HTTP/1.1" 304 -
[wyze5] 📡 Getting 180kb/s HD stream (H264/30fps) via LAN mode (WiFi: 68%) FW: 4.36.9.139 🔒 (DTLS) (2/3)
[wyze5] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[ravine] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 90%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[ravine] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[wyze5] FFMPEG stopped
[pool] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 96%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[pool] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[pool] FFMPEG stopped
[back-garage] 📡 Getting 180kb/s HD stream (H264/20fps) via LAN mode (WiFi: 94%) FW: 4.36.10.3406 🔒 (DTLS) (2/3)
[ravine] FFMPEG stopped
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:30] "GET /img/wyze5.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:30] "GET /static/notavailable.svg HTTP/1.1" 304 -
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Wyze5 on 192.168.3.48
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:30] "GET /img/wyze5.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.6 - - [28/Jul/2023 22:48:30] "GET /static/notavailable.svg HTTP/1.1" 304 -
[back-garage] FFMPEG stopped
[wyze5] 📡 Getting 180kb/s HD stream (H264/30fps) via LAN mode (WiFi: 69%) FW: 4.36.9.139 🔒 (DTLS) (2/3)
[wyze5] WARNING: Skipping smaller frame at start of stream (frame_size=1)
`

All of my cameras have firmware updates but I've been wary to do that due to past issues with wyzecam not working after updating firmware.  I've tried do clear cache and reconnect - pull a fresh image with docker-compose, etc... how come the wyze app works, but the wyzebridge connection can't work anymore?

**Comment by mrlt8** [comment]
Will look into this! It seems like it's able to connect to the cameras, but struggling to get the video frames.

Did this start after updating the bridge? There were some bitrate related changes introduced in v2.3.12. Does rolling back to v2.3.11 help?

**Comment by gleep52** [comment]
Sadly - I’m not sure - I have my compose file set to pull latest and never had an issue.  Was curious if I should stay on 4.36.10 or if perhaps I was supposed to upgrade to .11 or such.  I will figure out how to roll back to that version and let you know.
On Jul 28, 2023 at 7:37 PM -0500, mrlt8 ***@***.***>, wrote:

Will look into this! It seems like it's able to connect to the cameras, but struggling to get the video frames.

Did this start after updating the bridge? There were some bitrate related changes introduced in v2.3.12. Does rolling back to v2.3.11 help?

**Comment by mrlt8** [comment]
I don't think the firmware version should matter if it was working in the past. 

You should be able to see the version of the bridge in the WebUI or the logs.  You can downgrade the bridge by setting the image tag in your docker-compose.yml:

`image: mrlt8/wyze-bridge:2.3.11`

**Comment by gleep52** [comment]
yes rolling back to 2.3.11 seems to bring my cameras back to life.  

Any word on if it's safe to update firmware to the latest for security and stability - or is there confirmation that wyze 4.36.11 isn't compatible?

**Comment by gleep52** [comment]
It seems if I close the webpage to the wyze-bridge site (port5000 default) and restart the docker - then blue iris is mostly stable and can see the cameras... I've never had this issue in the past though.  

I updated the docker to the latest and as long as I have the webpage closed - things appear to be working properly still.

**Comment by TechToc23** [comment]
> yes rolling back to 2.3.11 seems to bring my cameras back to life.
> 
> Any word on if it's safe to update firmware to the latest for security and stability - or is there confirmation that wyze 4.36.11 isn't compatible?
> 
> EDIT - after I closed the webpage confirming cameras were working - the stream appears to not work on my blue iris server which is what I use wyzebridge for... if I open the webpage again and start the playback of the cameras there - then blue iris can see the streams again?

I was having the same problems. Cameras dropping out, not reachable,streams not working. I rolled back to 2.3.11 and everything is working great now.
