### ISSUE TITLE
[Bug?] Python Errors/Cams wont load until I load Bridge page/Invalid command: topic=

### ISSUE THREAD

**Issue by keawepoo** [mrlt8/docker-wyze-bridge#958]
Cams wont load until I load Bridge page...

```
Exception in thread Thread-5671:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/app/wyzecam/tutk/tutk_ioctl_mux.py", line 288, in run
    raise tutk.TutkError(actual_len)
wyzecam.tutk.tutk.TutkError: AV_ER_CLIENT_EXIT
[back-yard-cam-2] [CONTROL] AV_ER_CLIENT_EXIT
[back-yard-cam-2] Stream did not receive a frame for over 15s
bash: line 1: echo: write error: Interrupted system call
bash: line 1: echo: write error: Interrupted system call
bash: line 1: echo: write error: Interrupted system call
bash: line 1: echo: write error: Interrupted system call
bash: line 1: echo: write error: Interrupted system call
[front-yard-2] [CONTROL] Attempting to GET: caminfo
[front-yard-2] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
bash: line 1: echo: write error: Interrupted system call
[front-yard-1] [CONTROL] Attempting to GET: caminfo
[front-yard-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[side-cam-1] [CONTROL] Attempting to GET: caminfo
[side-cam-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[back-yard-cam-3] [CONTROL] Attempting to GET: caminfo
[back-yard-cam-3] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
bash: line 1: echo: write error: Interrupted system call
[back-yard-cam-1] [CONTROL] Attempting to GET: caminfo
[back-yard-cam-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[living-room-cam-2] [CONTROL] Attempting to GET: caminfo
[living-room-cam-2] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:31:02] "GET / HTTP/1.1" 200 -
[front-yard-2] [CONTROL] Attempting to GET: caminfo
[front-yard-2] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
bash: line 1: echo: write error: Interrupted system call
[front-yard-1] [CONTROL] Attempting to GET: caminfo
[front-yard-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[side-cam-1] [CONTROL] Attempting to GET: caminfo
[side-cam-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[back-yard-cam-3] [CONTROL] Attempting to GET: caminfo
[back-yard-cam-3] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
bash: line 1: echo: write error: Interrupted system call
[back-yard-cam-1] [CONTROL] Attempting to GET: caminfo
[back-yard-cam-1] [CONTROL] ERROR - Invalid command: topic='caminfo' not found cmd=('caminfo', '')
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 📕 Client stopped reading from d-1-sub
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 📕 Client stopped reading from -sub
[WyzeBridge] ⚠️ Expired token?
[WyzeBridge] ♻️ Refreshing tokens
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:00] "GET /img/side-cam-2-sub.jpg HTTP/1.1" 307 -
[WyzeBridge] 📖 New client reading from front-yard-1
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:01] "GET /img/front-yard-1.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from side-cam-1-sub
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:01] "GET /img/front-yard-2-sub.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from side-cam-1
[WyzeBridge] 📕 Client stopped reading from front-yard-1
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:01] "GET /img/side-cam-1-sub.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from back-yard-cam-3-sub
[WyzeBridge] 📕 Client stopped reading from side-cam-1-sub
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:02] "GET /img/side-cam-1.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from back-yard-cam-3
[WyzeBridge] 📕 Client stopped reading from front-yard-2-sub
[WyzeBridge] 📕 Client stopped reading from side-cam-1
Connection closed by remote. Closing connection.
Connection closed by remote. Closing connection.
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:03] "GET /img/front-yard-1-sub.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:03] "GET /img/back-yard-cam-2-sub.jpg HTTP/1.1" 307 -
[WyzeBridge] ☁️ Pulling "back-yard-cam-2" thumbnail to /img/back-yard-cam-2.jpg
[WyzeBridge] 📕 Client stopped reading from front-yard-1-sub
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:03] "GET /img/back-yard-cam-2.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from back-yard-cam-1-sub
[kitchen-cam-sub] [-20015] AV_ER_SESSION_CLOSE_BY_REMOTE
Connection closed by remote. Closing connection.
Connection closed by remote. Closing connection.
Connection closed by remote. Closing connection.
Connection closed by remote. Closing connection.
[kitchen-cam] ☁️ Camera is connected via RELAY mode!!
[kitchen-cam] Stream may consume additional bandwidth!
[kitchen-cam] 📡 Getting 180kb/s HD stream (H264/20fps) via RELAY mode (WiFi: 86%) FW: 4.36.10.4054 🔒 (DTLS) (2/3)
[kitchen-cam] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[kitchen-cam-sub] Stream Stopped
[side-cam-2] [-20015] AV_ER_SESSION_CLOSE_BY_REMOTE
[side-cam-2] [-20015] AV_ER_SESSION_CLOSE_BY_REMOTE
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:04] "GET /img/back-yard-cam-1-sub.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from back-yard-cam-1
[WyzeBridge] 📕 Client stopped reading from back-yard-cam-1-sub
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Side Cam 2 on 192.168.2.23
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Kitchen Cam on 192.168.2.68
[back-yard-cam-2] [-20015] AV_ER_SESSION_CLOSE_BY_REMOTE
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:04] "GET /img/front-yard-2.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:04] "GET /img/living-room-cam-1-sub.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:04] "GET /img/living-room-cam-1.jpg HTTP/1.1" 307 -
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:04] "GET /img/kitchen-cam-sub.jpg HTTP/1.1" 307 -
[WyzeBridge] ☁️ Pulling "kitchen-cam" thumbnail to /img/kitchen-cam.jpg
[side-cam-2] ☁️ Camera is connected via RELAY mode!!
[side-cam-2] Stream may consume additional bandwidth!
[side-cam-2] 📡 Getting 180kb/s HD stream (H264/20fps) via RELAY mode (WiFi: 84%) FW: 4.36.10.4054 🔒 (DTLS) (2/3)
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:05] "GET /img/back-yard-cam-3-sub.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from living-room-cam-2-sub
[side-cam-2] WARNING: Skipping smaller frame at start of stream (frame_size=1)
[side-cam-2-sub] ☁️ Camera is connected via RELAY mode!!
[side-cam-2-sub] Stream may consume additional bandwidth!
[side-cam-2-sub] 📡 Getting 30kb/s SD stream (H264/20fps) via RELAY mode (WiFi: 84%) FW: 4.36.10.4054 🔒 (DTLS) (2/3)
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:05] "GET /img/kitchen-cam.jpg HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from living-room-cam-2
[WyzeBridge] 🎉 Connecting to WyzeCam V3 - Back Yard Cam 2 on 192.168.2.18
[back-yard-cam-2-sub] ☁️ Camera is connected via RELAY mode!!
[back-yard-cam-2-sub] Stream may consume additional bandwidth!
[back-yard-cam-2-sub] 📡 Getting 30kb/s SD stream (H264/20fps) via RELAY mode (WiFi: 79%) FW: 4.36.10.4054 🔒 (DTLS) (2/3)
[WyzeBridge] 📕 Client stopped reading from front-yard-2
[WyzeBridge] ✅ '/back-yard-cam-2-sub stream is UP! (3/3)
[WyzeBridge] ✅ '/kitchen-cam stream is UP! (3/3)
[WyzeBridge] 📕 Client stopped reading from back-yard-cam-3-sub
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:05] "GET /img/back-yard-cam-1.jpg HTTP/1.1" 200 -
[WyzeBridge] 192.168.1.100 - - [12/Aug/2023 00:32:05] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] ✅ '/side-cam-2 stream is UP! (3/3)
```

**Comment by keawepoo** [comment]
any updates?

**Comment by mrlt8** [comment]
Can you try the latest version? You may also want to set `ON_DEMAND=false`
