### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by chrisbergeron** [mrlt8/docker-wyze-bridge#959]
I'm getting the following:

```
wyze-bridge  | 🚀 DOCKER-WYZE-BRIDGE v2.3.14
wyze-bridge  |
wyze-bridge  | [WyzeBridge] ♻️ Clearing local cache...
wyze-bridge  | Traceback (most recent call last):
wyze-bridge  |   File "/usr/local/bin/flask", line 8, in <module>
wyze-bridge  |     sys.exit(main())
wyze-bridge  |              ^^^^^^
wyze-bridge  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
wyze-bridge  |     cli.main()
... snip ...
wyze-bridge  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 63, in find_best_app
wyze-bridge  |     app = app_factory()
wyze-bridge  |           ^^^^^^^^^^^^^
wyze-bridge  |   File "/app/frontend.py", line 38, in create_app
wyze-bridge  |     wb.start()
wyze-bridge  |   File "/usr/local/lib/python3.11/threading.py", line 957, in start
wyze-bridge  |     _start_new_thread(self._bootstrap, ())
wyze-bridge  | RuntimeError: can't start new thread
```

I just upgraded from 1.11.  I'm using `docker-compose.yml` with `latest` image tag.  I have `FRESH_DATA=true`.  

Here's my environment info:

```bash
$ docker -v
Docker version 1.13.1, build 7d71120/1.13.1

$ docker-compose -v
Docker Compose version v2.3.4

$ rpm -qa | grep libseccomp
libseccomp-2.3.1-4.el7.x86_64

$ cat /etc/os-release | grep Cent
NAME="CentOS Linux"
PRETTY_NAME="CentOS Linux 7 (Core)"
CENTOS_MANTISBT_PROJECT="CentOS-7"

$ uname -a
Linux nas-04 5.13.4-1.el7.elrepo.x86_64 #1 SMP Wed Jul 21 23:02:00 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

My `docker/config.json`:

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "REMOVED"
		}
	},
	"psFormat": "table {{.ID}}\\t{{.Image}}\\t{{.Status}}\\t{{.Names}}"
}
```

These are my images:

```plaintext
docker image ls|grep wyze
docker.io/mrlt8/wyze-bridge                        latest              1215a7b5ef17        5 days ago          232 MB
docker.io/mrlt8/wyze-bridge                        <none>              ac1f81edda17        7 months ago        208 MB
docker.io/mrlt8/wyze-bridge                        <none>              dbdbc44ef2a7        16 months ago       222 MB
```

I restarted the container today and I started getting an auth error:

```
wyze-bridge  | 2023/08/11 20:03:29 [WyzeBridge] 🚀 STARTING DOCKER-WYZE-BRIDGE v1.11.1
... snip ...
wyze-bridge  | 2023/08/11 20:03:30 [WyzeBridge] 403 Client Error: Forbidden for url: https://auth-prod.api.wyze.com/user/login
```

So, after reading some of the issues in here, I figured I would upgrade the container.

Any ideas?   I really appreciate this software (and I'm a very happy donor).

**Comment by mrlt8** [comment]
The thread issue is potentially related to #909 and you'll need to update your host machine for compatibility with the `bookworm` image that we're using as the base.

`https://auth-prod.api.wyze.com/user/login` is the old authentication endpoint that wyze has deprecated, so you will need to be on 2.3.x or higher.

**Comment by chrisbergeron** [comment]
After reading more I learned that I need to upgrade docker.  For posterity, I used these steps:
for Centos 7.9
https://docs.docker.com/engine/install/centos/

https://docs.docker.com/engine/install/linux-postinstall/

You will have to recreate or re-configure your other containers after upgrading docker.

**Comment by chrisbergeron** [comment]
Yep, after upgrading docker to the latest version, the app works great!  Even better than before because it's much more responsive and there's very little lag on the cameras.  

```bash
🚀 DOCKER-WYZE-BRIDGE v2.3.14

[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] 🔍 Could not find local cache for 'auth'
 * Serving Flask app 'frontend'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.96.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding cam4 [WYZECP1_JEF]
[WyzeBridge] [+] Adding Garage Pan Cam 4 [HL_PAN3]
[WyzeBridge] [+] Adding Office Cam [HL_PAN3]
[WyzeBridge] [+] Adding Pan Cam v3 [HL_PAN3]
[WyzeBridge] [+] Adding Front Porch Cam [GW_GC2]
```

Kudos to all your hard work!!!
